const {PDFDocument,degrees}=PDFLib;
pdfjsLib.GlobalWorkerOptions.workerSrc="https://cdnjs.cloudflare.com/ajax/libs/pdf.js/3.11.174/pdf.worker.min.js";
const q=s=>document.querySelector(s),download=(bytes,name,type="application/pdf")=>{const blob=new Blob([bytes],{type}),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000)};
document.querySelectorAll(".pdf-tabs button").forEach(button=>button.onclick=()=>{document.querySelectorAll(".pdf-tabs button").forEach(x=>x.classList.remove("active"));document.querySelectorAll(".pdf-panel").forEach(x=>x.classList.remove("active"));button.classList.add("active");q("#"+button.dataset.panel).classList.add("active")});
function showFiles(input,target){q(target).innerHTML=[...input.files].map((f,i)=>`<div><span>${i+1}. ${f.name}</span><small>${(f.size/1048576).toFixed(2)} MB</small></div>`).join("")}
q("#mergeFiles").onchange=e=>showFiles(e.target,"#mergeList");q("#imageFiles").onchange=e=>showFiles(e.target,"#imageList");
q("#mergeButton").onclick=async()=>{const files=[...q("#mergeFiles").files],status=q("#mergeStatus");if(files.length<2){status.textContent="Choose at least two PDF files.";return}status.textContent="Merging…";try{const out=await PDFDocument.create();for(const file of files){const source=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:true});const pages=await out.copyPages(source,source.getPageIndices());pages.forEach(p=>out.addPage(p))}download(await out.save(),"smartconvert-merged.pdf");status.textContent=`Done — ${out.getPageCount()} pages merged.`}catch{status.textContent="Could not merge these PDFs. A file may be encrypted or damaged."}};
function parsePages(text,total){const set=new Set();for(const part of text.split(",").map(x=>x.trim()).filter(Boolean)){if(part.includes("-")){let[a,b]=part.split("-").map(Number);if(a>b)[a,b]=[b,a];for(let i=a;i<=b;i++)if(i>=1&&i<=total)set.add(i-1)}else{const n=Number(part);if(n>=1&&n<=total)set.add(n-1)}}return [...set]}
q("#splitButton").onclick=async()=>{const file=q("#splitFile").files[0],status=q("#splitStatus");if(!file){status.textContent="Choose a PDF first.";return}status.textContent="Extracting…";try{const source=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:true}),indices=parsePages(q("#pageRange").value,source.getPageCount());if(!indices.length){status.textContent=`Enter valid pages from 1 to ${source.getPageCount()}.`;return}const out=await PDFDocument.create(),pages=await out.copyPages(source,indices);pages.forEach(p=>out.addPage(p));download(await out.save(),"smartconvert-extracted-pages.pdf");status.textContent=`Done — ${indices.length} page(s) extracted.`}catch{status.textContent="Could not extract pages from this PDF."}};
q("#rotateButton").onclick=async()=>{const file=q("#rotateFile").files[0],status=q("#rotateStatus");if(!file){status.textContent="Choose a PDF first.";return}status.textContent="Rotating…";try{const doc=await PDFDocument.load(await file.arrayBuffer(),{ignoreEncryption:true}),angle=Number(q("#rotation").value);doc.getPages().forEach(page=>page.setRotation(degrees((page.getRotation().angle+angle)%360)));download(await doc.save(),"smartconvert-rotated.pdf");status.textContent=`Done — ${doc.getPageCount()} page(s) rotated.`}catch{status.textContent="Could not rotate this PDF."}};
q("#renderButton").onclick=async()=>{const file=q("#renderFile").files[0],status=q("#renderStatus");if(!file){status.textContent="Choose a PDF first.";return}status.textContent="Rendering page…";try{const pdf=await pdfjsLib.getDocument({data:new Uint8Array(await file.arrayBuffer())}).promise,pageNumber=Number(q("#renderPage").value);if(pageNumber<1||pageNumber>pdf.numPages){status.textContent=`Choose a page from 1 to ${pdf.numPages}.`;return}const page=await pdf.getPage(pageNumber),viewport=page.getViewport({scale:2.2}),canvas=document.createElement("canvas"),ctx=canvas.getContext("2d");canvas.width=viewport.width;canvas.height=viewport.height;await page.render({canvasContext:ctx,viewport}).promise;const type=q("#renderFormat").value,blob=await new Promise(r=>canvas.toBlob(r,type,.92)),url=URL.createObjectURL(blob),a=document.createElement("a");a.href=url;a.download=`pdf-page-${pageNumber}.${type==="image/png"?"png":"jpg"}`;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);status.textContent=`Done — page ${pageNumber} converted.`}catch{status.textContent="Could not render this PDF page."}};
q("#imagePdfButton").onclick=async()=>{const files=[...q("#imageFiles").files],status=q("#imagePdfStatus");if(!files.length){status.textContent="Choose at least one JPG or PNG image.";return}status.textContent="Creating PDF…";try{const doc=await PDFDocument.create();for(const file of files){const bytes=await file.arrayBuffer(),image=file.type==="image/png"?await doc.embedPng(bytes):await doc.embedJpg(bytes),page=doc.addPage([image.width,image.height]);page.drawImage(image,{x:0,y:0,width:image.width,height:image.height})}download(await doc.save(),"smartconvert-images.pdf");status.textContent=`Done — ${files.length} image(s) added.`}catch{status.textContent="Could not create a PDF from these images."}};
