const $=s=>document.querySelector(s),drop=$("#drop"),input=$("#fileInput"),workspace=$("#workspace"),preview=$("#preview"),width=$("#width"),height=$("#height"),quality=$("#quality"),result=$("#result"),error=$("#error");let file=null,url="",outputUrl="",format="image/webp",locked=true,ow=0,oh=0;const labels={"image/jpeg":"JPG","image/png":"PNG","image/webp":"WEBP"},ext={"image/jpeg":"jpg","image/png":"png","image/webp":"webp"};
function size(n){
  if(n<1024)return n+" B";
  if(n<1048576)return (n/1024).toFixed(1)+" KB";
  return (n/1048576).toFixed(2)+" MB";
}
function load(f){
  error.textContent="";
  if(!f||!f.type.startsWith("image/")){error.textContent="Choose a compatible image.";return;}
  if(f.size>26214400){error.textContent="The file is larger than 25 MB.";return;}
  file=f;if(url)URL.revokeObjectURL(url);url=URL.createObjectURL(f);preview.src=url;
  const img=new Image();
  img.onload=()=>{ow=img.naturalWidth;oh=img.naturalHeight;width.value=ow;height.value=oh;$("#fileDetails").textContent=`${size(f.size)} · ${ow} × ${oh}px`;};
  img.src=url;$("#fileName").textContent=f.name;drop.classList.add("hidden");workspace.classList.remove("hidden");result.classList.add("hidden");
}
drop.onclick=()=>input.click();drop.onkeydown=e=>{if(e.key==="Enter"||e.key===" ")input.click()};input.onchange=e=>load(e.target.files[0]);["dragenter","dragover"].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.add("dragging")}));["dragleave","drop"].forEach(x=>drop.addEventListener(x,e=>{e.preventDefault();drop.classList.remove("dragging")}));drop.ondrop=e=>load(e.dataTransfer.files[0]);
document.querySelectorAll(".formats button").forEach(b=>b.onclick=()=>{document.querySelectorAll(".formats button").forEach(x=>x.classList.remove("active"));b.classList.add("active");format=b.dataset.format;$("#convert").textContent=`Convert to ${labels[format]}`;$("#qualityBox").classList.toggle("hidden",format==="image/png");result.classList.add("hidden")});quality.oninput=()=>{$("#qualityValue").textContent=quality.value+"%";result.classList.add("hidden")};width.oninput=()=>{if(locked&&width.value)height.value=Math.round(width.value*oh/ow);result.classList.add("hidden")};height.oninput=()=>{if(locked&&height.value)width.value=Math.round(height.value*ow/oh);result.classList.add("hidden")};$("#ratio").onclick=()=>{locked=!locked;$("#ratio").textContent=locked?"Ratio locked":"Free resize"};
$("#remove").onclick=()=>{file=null;if(url)URL.revokeObjectURL(url);drop.classList.remove("hidden");workspace.classList.add("hidden");input.value=""};$("#convert").onclick=async()=>{if(!file||!+width.value||!+height.value)return;const button=$("#convert");button.disabled=true;button.textContent="Converting…";error.textContent="";try{const img=new Image();img.src=url;await img.decode();const canvas=document.createElement("canvas");canvas.width=+width.value;canvas.height=+height.value;const ctx=canvas.getContext("2d");ctx.imageSmoothingEnabled=true;ctx.imageSmoothingQuality="high";if(format==="image/jpeg"){ctx.fillStyle="#fff";ctx.fillRect(0,0,canvas.width,canvas.height)}ctx.drawImage(img,0,0,canvas.width,canvas.height);const blob=await new Promise(r=>canvas.toBlob(r,format,format==="image/png"?undefined:quality.value/100));if(outputUrl)URL.revokeObjectURL(outputUrl);outputUrl=URL.createObjectURL(blob);const saved=blob.size<file.size?` · ${Math.round((1-blob.size/file.size)*100)}% smaller`:"";$("#resultInfo").textContent=size(blob.size)+saved;const a=$("#download");a.href=outputUrl;a.download=(file.name.replace(/\.[^/.]+$/,"")||"converted-image")+"."+ext[format];result.classList.remove("hidden")}catch{error.textContent="We couldn't convert this image. Try another format."}finally{button.disabled=false;button.textContent=`Convert to ${labels[format]}`}};
